services:
  - type: worker
    name: telegram-expense-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: SPREADSHEET_ID
        sync: false 